#!/usr/bin/env bash
#
#
VERSION="1.0.2"
case $(uname -m) in
   armv6l|armv7l)
		sudo rm -f /usr/bin/chirpw
      sudo ln -s chirp/Chirp-daily-*-armhf.AppImage /usr/bin/chirpw
      ;;
   aarch64)
		sudo rm -f /usr/bin/chirpw
		sudo ln -s chirp/Chirp-daily-*-aarch64.AppImage /usr/bin/chirpw
      ;;
   *)
      echo "Unable to determine architecture"
      exit 1
      ;;
esac
sudo cp -f chirp/usr/share/pixmaps/*.png /usr/share/pixmaps/
sudo cp -f chirp/usr/share/applications/*.desktop /usr/share/applications/
exit 0
